# Generated by Django 3.0.1 on 2020-01-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_center',
            old_name='news_is',
            new_name='news_id',
        ),
    ]
