# Generated by Django 3.0.1 on 2020-01-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20200106_2325'),
        ('front', '0002_auto_20200106_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_center',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.news'),
        ),
        migrations.AlterField(
            model_name='user_center',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.users'),
        ),
    ]
