# Generated by Django 3.0.1 on 2020-01-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yule',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
