# Generated by Django 3.0.1 on 2020-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yule',
            name='category',
            field=models.CharField(default='娱乐', max_length=20),
        ),
    ]
