# Generated by Django 3.0.1 on 2020-01-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_yule_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='caijing',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='娱乐', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='guoji',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='娱乐', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='junshi',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='娱乐', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='keji',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='娱乐', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='lishi',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='娱乐', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tiyu',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='娱乐', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
