# Generated by Django 3.0.1 on 2020-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('is_superuser', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
