# Generated by Django 3.0.1 on 2020-01-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200104_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lishi',
            new_name='shehui',
        ),
        migrations.RenameModel(
            old_name='tiyu',
            new_name='shuping',
        ),
    ]
