# Generated by Django 3.0.1 on 2020-01-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20200105_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='caijing',
        ),
        migrations.DeleteModel(
            name='guoji',
        ),
        migrations.DeleteModel(
            name='junshi',
        ),
        migrations.DeleteModel(
            name='keji',
        ),
        migrations.DeleteModel(
            name='shehui',
        ),
        migrations.DeleteModel(
            name='shuping',
        ),
        migrations.DeleteModel(
            name='yule',
        ),
    ]
