# Generated by Django 3.0.1 on 2020-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20200105_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
